services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fsh
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: src/Playground/Playground.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseOptions__ConnectionString: "Host=postgres;Port=5432;Database=fsh;Username=postgres;Password=password"
      CachingOptions__Redis: "redis:6379"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317"

volumes:
  postgres-data:
