using FSH.Modules.Auditing.Contracts;
using FSH.Modules.Auditing.Contracts.Dtos;
using Integration.Tests.Infrastructure;

namespace Integration.Tests.Tests.Auditing;

/// <summary>
/// Covers the exception-audit read path (<c>GetExceptionAuditsQueryHandler</c>
/// + validator) and pulls up filter/paging coverage on the list, security and
/// summary handlers. Exception audits are generated by hitting an endpoint that
/// throws (a by-id lookup for a missing record raises KeyNotFoundException,
/// which the AuditHttpMiddleware records as an Api-area Exception event at
/// Error severity before the global handler maps it to 404).
/// </summary>
[Collection(FshCollectionDefinition.Name)]
public sealed class AuditExceptionAndFilterTests
{
    private readonly AuthHelper _auth;

    public AuditExceptionAndFilterTests(FshWebApplicationFactory factory)
    {
        _auth = new AuthHelper(factory);
    }

    #region GetExceptionAudits

    [Fact]
    public async Task GetExceptionAudits_Should_ReturnRows_When_ExceptionAuditExists()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();
        await TriggerApiExceptionAsync(client);

        // Act + Assert (poll: the exception audit is written asynchronously)
        var rows = await PollExceptionsAsync(client, string.Empty,
            r => r.EventType == AuditEventType.Exception);

        rows.ShouldNotBeEmpty();
        rows.ShouldAllBe(r => r.EventType == AuditEventType.Exception);
    }

    [Fact]
    public async Task GetExceptionAudits_Should_FilterByArea_When_ApiAreaRequested()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();
        await TriggerApiExceptionAsync(client);

        // Act — Api-area filter exercises the payload ILIKE branch.
        var rows = await PollExceptionsAsync(client, $"area={ExceptionArea.Api}",
            r => r.EventType == AuditEventType.Exception);

        // Assert
        rows.ShouldNotBeEmpty();
    }

    [Fact]
    public async Task GetExceptionAudits_Should_FilterBySeverity_When_ErrorRequested()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();
        await TriggerApiExceptionAsync(client);

        // Act — KeyNotFoundException classifies as Error severity.
        var rows = await PollExceptionsAsync(client, $"severity={AuditSeverity.Error}",
            r => r.Severity == AuditSeverity.Error);

        // Assert
        rows.ShouldNotBeEmpty();
        rows.ShouldAllBe(r => r.Severity == AuditSeverity.Error);
    }

    [Fact]
    public async Task GetExceptionAudits_Should_FilterByExceptionType_When_TypeProvided()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();
        await TriggerApiExceptionAsync(client);

        // Act — exercises the exceptionType payload ILIKE branch.
        var rows = await PollExceptionsAsync(client, "exceptionType=System.Collections.Generic.KeyNotFoundException",
            r => r.EventType == AuditEventType.Exception);

        // Assert
        rows.ShouldNotBeEmpty();
    }

    [Fact]
    public async Task GetExceptionAudits_Should_ReturnEmpty_When_UnknownExceptionType()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();
        await TriggerApiExceptionAsync(client);

        // Act
        var rows = await AuditTestHelper.GetListAsync(
            client, "/exceptions?exceptionType=Some.Type.That.Does.Not.Exist");

        // Assert
        rows.ShouldBeEmpty();
    }

    [Fact]
    public async Task GetExceptionAudits_Should_FilterByRouteOrLocation_When_RouteProvided()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();
        await TriggerApiExceptionAsync(client);

        // Act — the recorded routeOrLocation is the audits base path.
        var rows = await PollExceptionsAsync(
            client, $"routeOrLocation={Uri.EscapeDataString(TestConstants.AuditsBasePath)}",
            r => r.EventType == AuditEventType.Exception);

        // Assert
        rows.ShouldNotBeEmpty();
    }

    [Fact]
    public async Task GetExceptionAudits_Should_Return400_When_FromAfterTo()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();
        string from = DateTime.UtcNow.ToString("o");
        string to = DateTime.UtcNow.AddDays(-1).ToString("o");

        // Act
        var response = await client.GetAsync(
            $"{TestConstants.AuditsBasePath}/exceptions?fromUtc={Uri.EscapeDataString(from)}&toUtc={Uri.EscapeDataString(to)}");

        // Assert
        response.StatusCode.ShouldBe(HttpStatusCode.BadRequest);
    }

    #endregion

    #region GetSecurityAudits filters

    [Fact]
    public async Task GetSecurityAudits_Should_ReturnLoginEvents_When_TokenIssued()
    {
        // Arrange — issuing a token records a Security audit.
        await _auth.GetRootAdminTokenAsync();
        using var client = await _auth.CreateRootAdminClientAsync();

        // Act
        var rows = await PollSecurityAsync(client, string.Empty,
            r => r.EventType == AuditEventType.Security);

        // Assert
        rows.ShouldNotBeEmpty();
        rows.ShouldAllBe(r => r.EventType == AuditEventType.Security);
    }

    [Fact]
    public async Task GetSecurityAudits_Should_FilterByAction_When_TokenIssuedRequested()
    {
        // Arrange
        await _auth.GetRootAdminTokenAsync();
        using var client = await _auth.CreateRootAdminClientAsync();

        // Act — exercises the action payload ILIKE branch.
        var rows = await PollSecurityAsync(client, $"action={SecurityAction.TokenIssued}",
            r => r.EventType == AuditEventType.Security);

        // Assert
        rows.ShouldNotBeEmpty();
    }

    [Fact]
    public async Task GetSecurityAudits_Should_ReturnEmpty_When_UnknownUser()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();

        // Act — userId filter with a value that never appears.
        var rows = await AuditTestHelper.GetListAsync(
            client, $"/security?userId={Guid.NewGuid()}");

        // Assert
        rows.ShouldBeEmpty();
    }

    [Fact]
    public async Task GetSecurityAudits_Should_HonorDateWindow_When_FromInFuture()
    {
        // Arrange
        await _auth.GetRootAdminTokenAsync();
        using var client = await _auth.CreateRootAdminClientAsync();
        string future = DateTime.UtcNow.AddDays(1).ToString("o");

        // Act
        var rows = await AuditTestHelper.GetListAsync(
            client, $"/security?fromUtc={Uri.EscapeDataString(future)}");

        // Assert
        rows.ShouldBeEmpty();
    }

    #endregion

    #region GetAudits filters / paging

    [Fact]
    public async Task GetAudits_Should_FilterByEventType_When_ActivityRequested()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();
        await AuditTestHelper.GenerateActivityAuditAsync(client);

        // Act
        var page = await AuditTestHelper.GetAuditsPageAsync(
            client, extraQuery: $"eventType={AuditEventType.Activity}");

        // Assert
        page.Items.ShouldNotBeEmpty();
        page.Items.ShouldAllBe(r => r.EventType == AuditEventType.Activity);
    }

    [Fact]
    public async Task GetAudits_Should_FilterBySource_When_SourceProvided()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();
        var seed = await AuditTestHelper.GenerateActivityAuditAsync(client);
        seed.Source.ShouldNotBeNull();

        // Act
        var page = await AuditTestHelper.GetAuditsPageAsync(
            client, extraQuery: $"source={Uri.EscapeDataString(seed.Source!)}");

        // Assert
        page.Items.ShouldNotBeEmpty();
        page.Items.ShouldAllBe(r => r.Source == seed.Source);
    }

    [Fact]
    public async Task GetAudits_Should_FilterByCorrelationId_When_Provided()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();
        var seed = await AuditTestHelper.GenerateActivityAuditAsync(client);

        // Act
        var page = await AuditTestHelper.GetAuditsPageAsync(
            client, extraQuery: $"correlationId={Uri.EscapeDataString(seed.CorrelationId!)}");

        // Assert
        page.Items.ShouldNotBeEmpty();
        page.Items.ShouldAllBe(r => r.CorrelationId == seed.CorrelationId);
    }

    [Fact]
    public async Task GetAudits_Should_FilterByTraceId_When_Provided()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();
        var seed = await AuditTestHelper.GenerateActivityAuditAsync(client);

        // Act
        var page = await AuditTestHelper.GetAuditsPageAsync(
            client, extraQuery: $"traceId={Uri.EscapeDataString(seed.TraceId!)}");

        // Assert
        page.Items.ShouldNotBeEmpty();
        page.Items.ShouldAllBe(r => r.TraceId == seed.TraceId);
    }

    [Fact]
    public async Task GetAudits_Should_SearchPayload_When_SearchTermProvided()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();
        await AuditTestHelper.GenerateActivityAuditAsync(client);

        // Act — search hits the UserName/Source/PayloadJson ILIKE branch.
        var page = await AuditTestHelper.GetAuditsPageAsync(
            client, extraQuery: $"search={Uri.EscapeDataString("audits")}");

        // Assert
        page.ShouldNotBeNull();
        page.TotalCount.ShouldBeGreaterThanOrEqualTo(0);
    }

    [Fact]
    public async Task GetAudits_Should_FilterBySeverity_When_InformationRequested()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();
        await AuditTestHelper.GenerateActivityAuditAsync(client);

        // Act
        var page = await AuditTestHelper.GetAuditsPageAsync(
            client, extraQuery: $"severity={AuditSeverity.Information}");

        // Assert
        page.Items.ShouldAllBe(r => r.Severity == AuditSeverity.Information);
    }

    [Fact]
    public async Task GetAudits_Should_ClampWindow_When_OnlyFromSuppliedAndOld()
    {
        // Arrange — supplying only fromUtc (well beyond MaxWindow) bypasses the
        // validator's both-endpoints rule and exercises the handler's clamp to
        // the 90-day MaxWindow. A both-endpoints range >90d would 400 instead.
        using var client = await _auth.CreateRootAdminClientAsync();
        await AuditTestHelper.GenerateActivityAuditAsync(client);
        string from = DateTime.UtcNow.AddDays(-400).ToString("o");

        // Act
        var page = await AuditTestHelper.GetAuditsPageAsync(
            client, extraQuery: $"fromUtc={Uri.EscapeDataString(from)}");

        // Assert — clamped, still a valid bounded response that returns rows.
        page.ShouldNotBeNull();
        page.PageNumber.ShouldBe(1);
        page.Items.ShouldNotBeEmpty();
    }

    [Fact]
    public async Task GetAudits_Should_Return400_When_BothEndpointsExceedMaxWindow()
    {
        // Arrange — a both-endpoints window wider than the 90-day MaxWindow is
        // rejected by the validator (defence-in-depth over the handler clamp).
        using var client = await _auth.CreateRootAdminClientAsync();
        string from = DateTime.UtcNow.AddDays(-400).ToString("o");
        string to = DateTime.UtcNow.ToString("o");

        // Act
        var response = await client.GetAsync(
            $"{TestConstants.AuditsBasePath}?pageNumber=1&pageSize=10&fromUtc={Uri.EscapeDataString(from)}&toUtc={Uri.EscapeDataString(to)}");

        // Assert
        response.StatusCode.ShouldBe(HttpStatusCode.BadRequest);
    }

    [Fact]
    public async Task GetAudits_Should_Return400_When_PageSizeInvalid()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();

        // Act — pageSize beyond the allowed maximum trips the paged-query validator.
        var response = await client.GetAsync(
            $"{TestConstants.AuditsBasePath}?pageNumber=1&pageSize=100000");

        // Assert
        response.StatusCode.ShouldBe(HttpStatusCode.BadRequest);
    }

    #endregion

    #region GetAuditSummary

    [Fact]
    public async Task GetAuditSummary_Should_AggregateByType_When_ActivityExists()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();
        await AuditTestHelper.GenerateActivityAuditAsync(client);

        // Act
        var response = await client.GetAsync($"{TestConstants.AuditsBasePath}/summary");

        // Assert
        response.StatusCode.ShouldBe(HttpStatusCode.OK);
        string body = await response.Content.ReadAsStringAsync();
        body.ShouldContain("eventsByType");
        body.ShouldContain("eventsBySeverity");
    }

    [Fact]
    public async Task GetAuditSummary_Should_ReturnOk_When_NarrowWindowProvided()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();
        string from = DateTime.UtcNow.AddHours(-1).ToString("o");
        string to = DateTime.UtcNow.ToString("o");

        // Act
        var response = await client.GetAsync(
            $"{TestConstants.AuditsBasePath}/summary?fromUtc={Uri.EscapeDataString(from)}&toUtc={Uri.EscapeDataString(to)}");

        // Assert
        response.StatusCode.ShouldBe(HttpStatusCode.OK);
    }

    [Fact]
    public async Task GetAuditSummary_Should_Return400_When_FromAfterTo()
    {
        // Arrange
        using var client = await _auth.CreateRootAdminClientAsync();
        string from = DateTime.UtcNow.ToString("o");
        string to = DateTime.UtcNow.AddDays(-1).ToString("o");

        // Act
        var response = await client.GetAsync(
            $"{TestConstants.AuditsBasePath}/summary?fromUtc={Uri.EscapeDataString(from)}&toUtc={Uri.EscapeDataString(to)}");

        // Assert
        response.StatusCode.ShouldBe(HttpStatusCode.BadRequest);
    }

    #endregion

    #region Helpers

    private static async Task TriggerApiExceptionAsync(HttpClient client)
    {
        // GET /audits/{guid} for a non-existent record throws KeyNotFoundException
        // inside the audited request, producing an Api-area Exception audit event.
        // The AuditHttpMiddleware writes the exception audit before the exception
        // propagates to the exception handler, so the audit is recorded regardless
        // of the final HTTP status the handler renders.
        var response = await client.GetAsync($"{TestConstants.AuditsBasePath}/{Guid.NewGuid()}");
        (await AuditTestHelper.IsNotFoundAsync(response)).ShouldBeTrue();
    }

    private static async Task<IReadOnlyList<AuditSummaryDto>> PollExceptionsAsync(
        HttpClient client, string query, Func<AuditSummaryDto, bool> predicate)
    {
        string relative = string.IsNullOrEmpty(query) ? "/exceptions" : $"/exceptions?{query}";
        for (int i = 0; i < AuditTestHelper.DefaultPollAttempts; i++)
        {
            var rows = await AuditTestHelper.GetListAsync(client, relative);
            if (rows.Any(predicate))
            {
                return rows;
            }

            await Task.Delay(AuditTestHelper.PollInterval);
        }

        throw new TimeoutException($"No exception audit matched within budget (query='{query}').");
    }

    private static async Task<IReadOnlyList<AuditSummaryDto>> PollSecurityAsync(
        HttpClient client, string query, Func<AuditSummaryDto, bool> predicate)
    {
        string relative = string.IsNullOrEmpty(query) ? "/security" : $"/security?{query}";
        for (int i = 0; i < AuditTestHelper.DefaultPollAttempts; i++)
        {
            var rows = await AuditTestHelper.GetListAsync(client, relative);
            if (rows.Any(predicate))
            {
                return rows;
            }

            await Task.Delay(AuditTestHelper.PollInterval);
        }

        throw new TimeoutException($"No security audit matched within budget (query='{query}').");
    }

    #endregion
}
